version: '2.1'

volumes:
  db_data:
    driver: 'local'

services:
  db:
    image: 'mysql:5.7'
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'api_platform'
      MYSQL_USER: 'api_platform'
      MYSQL_PASSWORD: 'api_platform'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - '3306:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
    healthcheck:
      test: ['CMD-SHELL', 'mysql --user=api_platform --password=api_platform -e "SHOW TABLES" api_platform']
      interval: '5s'
      timeout: '1s'
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    environment:
    - PMA_ARBITRARY=1
    links:
    - db:mysql
    restart: always
    ports:
    - 3308:80
    volumes:
    - /sessions

  php:
    build: '.'
    container_name: 'php'
    depends_on:
      db:
        condition: 'service_healthy'
    environment:
      SYMFONY_ENV: 'dev'
      XDEBUG_CONFIG: remote_host=10.254.254.254
      PHP_IDE_CONFIG: 'serverName=localhost'
    volumes:
      - './:/srv/api-platform'

  nginx:
    image: 'nginx:1.13-alpine'
    container_name: 'web'
    depends_on:
      php:
        condition: 'service_started'
    ports:
      - '8084:80'
    volumes_from:
      - php
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'

