api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api/v1'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
